version: '3'

services:
  turjuman:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8051:8051"
    volumes:
      - ./:/app
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - HOST=0.0.0.0
      - PORT=8051
      - DEV_RELOAD=true
      # - OLLAMA_BASE_URL=http://host.docker.internal:11434 # enable if you have ollama 
      # - LOCALAI_BASE_URL=http://host.docker.internal:5003 # enable if you have LMstudio, LLamacpp, kobolod ...etc 
    command: uvicorn src.server:app --host 0.0.0.0 --port 8051 --reload